export interface SettingSubItem {
  /** Directory/folder name used as the URL segment */
  slug: string;
  /** Human-readable display label */
  label: string;
  /** Full route path */
  href: string;
}

/**
 * Build-time manifest of setting subdirectories.
 *
 * This is auto-generated by `scripts/generate-settings-manifest.mjs`.
 * During development you can edit this file directly or run:
 *   node scripts/generate-settings-manifest.mjs
 */
export const settingsManifest: SettingSubItem[] = [
  { slug: "branches", label: "Branches", href: "/system/setting/branches" },
  { slug: "department", label: "Department", href: "/system/setting/department" },
  { slug: "permissions", label: "Permissions", href: "/system/setting/permissions" },
  { slug: "roles", label: "Roles", href: "/system/setting/roles" },
];

/** Convert a slug like "my-page" into a title like "My Page" */
export function slugToLabel(slug: string): string {
  return slug
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}
